### ISSUE TITLE
Date in miliseconds

### ISSUE THREAD

**Issue by Jeppes** [armada-ths/ais#134]
Can the backend send all timestamps in milliseconds instead of seconds? The tool we use for parsing json in android does not support seconds (and switching is not an option), so otherwise we would need to manually updating the fields. 
The same goes for frontend, if they ever forget to multiply by 1000 the dates will break.

**Comment by mictab** [comment]
Will be looked at 👍

**Comment by Tiseno** [comment]
Shouldn't unix time be in seconds?
This seems preposterous to me.

**Comment by purmonen** [comment]
On iOS we will need to divide by 1000 if we use milliseconds. Seconds is the base unit of time so I prefer that.

**Comment by mictab** [comment]
@apals @purmonen you two need to decide on this together with your devs :)

**Comment by walaro** [comment]
Unix time is per definition seconds in UTC, make sure to rename the function or add a separate function if you want to turn it into some kind of unstandardized, ungodly abomination.

**Comment by mictab** [comment]
So...

Android needs milliseconds
iOS wants seconds
Frontend wants/needs idk?

Would using a datestring be a compromise? See http://api.armada.nu/api/events for example.

**Comment by Jeppes** [comment]
Just send a date string like you did last year

**Comment by mictab** [comment]
@purmonen Is that okay with iOS too?

**Comment by Jeppes** [comment]
nevermind @mictab

**Comment by purmonen** [comment]
No, string is the worst format for dates. How are we supposed to use it? Just display the string as it comes from the server? In that case we can't do date logic like sorting on dates because that requires that you create date object. For instance, on iOS we have a function that scrolls you to the event closest to current time, that requires date logic. And if you send a string that should be converted to a date object on each platform then parsing a string is much more work than getting a unix timestamp.

**Comment by apals** [comment]
Unix timestamp in seconds it is.
